services:
#  app:
#    container_name: finance-system
#    image: finance-system
#    build: ./ # Path to Dockerfile
#    ports:
#      - "8080:8080" # Port exposed to host:port exposed in container
#    depends_on:
#      - PostgreSQL_DB

  PostgreSQL:
    image: postgres:alpine # PostgreSQL image, alpine version (lightweight)
    ports:
      - "6000:5432" # Port exposed to host:port exposed in container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_system

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672'
